project:
  type: "website"


website:
  title: "Seaside chats: Psychological safety"

  navbar:
    left:
      - text: "Placeholder"


format:
  html:
    theme: "cosmo"
    css: "styles.css"
    toc: true
