project:
  type: "website"


website:
  title: "Seaside chats: Psychological safety"

  navbar:
    left:
      - text: "Meetings"
        file: "meetings/index.md"


format:
  html:
    theme: "cosmo"
    css: "styles.css"
    toc: true
