# Build, and deploy to either GitHub Pages (production), or Netlify (PR previews)
name: "Build and deploy"

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Sets permissions of the GITHUB_TOKEN
permissions:
  # For GitHub Pages:
  pages: "write"
  id-token: "write"


# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true


# Default to bash in login mode
# https://github.com/mamba-org/provision-with-micromamba#IMPORTANT
defaults:
  run:
    shell: "bash -l {0}"


jobs:
  # Build job
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Quarto"
        uses: "quarto-dev/quarto-actions/setup@v2"

      - name: "Render Quarto website"
        run: "quarto render ."

      - name: "Upload site artifact"
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: "./_site"


  deploy:
    runs-on: "ubuntu-latest"
    needs: "build"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    steps:
      - name: "Deploy to GitHub Pages"
        id: "deployment"
        uses: "actions/deploy-pages@v4"
